### ISSUE TITLE
Context Window size

### ISSUE THREAD

**Issue by enricoros** [mistralai/client-js#2]
Hello, it would be great if either the API (preferred) or the documentation could contain the following:
 - **context window** size (input), in tokens
 - **max output tokens** per call (e.g. latest OpenAI models have a 4096 limit, while before it was context_window - max_tokens)

At least for the 3x Chat models, but even having guidance on the '-embed' will be of great help to developers.

Love your work!

**Comment by ishaan-jaff** [comment]
@Bam4d is the context window of mistral-embed also 32k? 

I could not find any info about this 

We need to track this here: https://github.com/BerriAI/litellm
