### ISSUE TITLE
CORS issues with frontend applications

### ISSUE THREAD

**Issue by themataleao** [mistralai/client-js#21]
Currently, the client-js is not usable within frontend applications directly since CORS is activated for the mistral API endpoint.

Are any open endpoints in sight for testing purposes?

**Comment by wordware-ai** [comment]
I made a workaround here https://github.com/mistralai/client-js/issues/4#issuecomment-1858858220
uses https://corsproxy.io
and https://www.npmjs.com/package/mistral-edge

**Comment by themataleao** [comment]
@wordware-ai thanks for that. I saw that the API complains about CORS but still sends a request back. The usage of Corsproxy seems also valid. Thanks for the tip.

Regarding your edge implementation that also looks nice.

I have rewritten the Mistral API client in Typescript: 
https://github.com/themataleao/mistralai-client-ts
https://www.npmjs.com/package/@ai-utils/mistral

I wanted initially to rewrite the Axios calls with fetch, but I wasn't able to do it. If you want to help me to rewrite it in my lib I would appreciate it :).

**Comment by lerela** [comment]
CORS headers are enabled so this should work now. 

However, you might run into issues if you are sending custom headers in the request. 

In that case, can you please let us know what additional legitimate headers you are looking to include?

**Comment by themataleao** [comment]
@lerela CORS issues are resolved. Thanks a lot!

No additional headers are required.

You can try it with this react app if interested: https://github.com/themataleao/mistralai-client-ts

**Comment by Bam4d** [comment]
We've also added a react example that uses fetch and not axios, also a bunch more fixes in there too :)

https://github.com/mistralai/client-js/tree/main/examples/chat-react

**Comment by themataleao** [comment]
@Bam4d looks sweet. :) No typescript though 🥲

Do you guys plan to rewrite the application in typescript?

**Comment by Bam4d** [comment]
We added a `client.d.ts` for use in typescript, but didn't want to force everyone into using typescript in the examples.

**Comment by themataleao** [comment]
@Bam4d in the end typescript will help you guys much more to maintain the library :). Examples are a nice bonus. It should also be mentioned that API keys should never be exposed to a client application.
