### ISSUE TITLE
Client is not working on NodeJS

### ISSUE THREAD

**Issue by amorphius** [mistralai/client-js#32]
When I put this line on NodeJS request handler it freezes my backend without creating client 
```
    const client = new MistralClient(apiKey);
```
simple JS script which is run via `node index.js` works fine though. Is there any caveats when using MistralClient on backend request handlers?

**Comment by Bam4d** [comment]
HI, Can you try our new version 0.0.10? If that is still not working can you provide a small example script? Thanks!

**Comment by Jey-molokoy** [comment]
As the endpoints are similar and as a workaround i used OpenAi client modifying the baseURL/
import {  mistralaiKey } from "../../config"

import OpenAI from "openai"

const mistralai = new OpenAI({
  apiKey: mistralaiKey,
  baseURL: "https://api.mistral.ai/v1",
})
HTH

**Comment by Jey-molokoy** [comment]
Same here.
Quick workaround, as the endpoints are the same, you can use the OpenAI client changing the base url and using your mistral Key:

```
import OpenAI from "openai"
import {  mistralaiKey } from "../../config"
const mistralAi = new OpenAI({
  apiKey: mistralaiKey,
  baseURL: "https://api.mistral.ai/v1",
})

const completion = await mistralAi.chat.completions.create({
...

```

**Comment by amorphius** [comment]
yes, it works in 0.0.10, thanks!
