### ISSUE TITLE
Typescript types pointing to wrong file

### ISSUE THREAD

**Issue by brenc** [mistralai/client-js#35]
Just installed the client. VS Code can't find TS types probably because in `package.json` this field is incorrect: `"types": "src/mistralai.d.ts"` when it should be `"types": "src/client.d.ts"`.

**Comment by brenc** [comment]
Ahh, I see a PR to fix this has been merged but a new release hasn't been issued yet.

**Comment by Bam4d** [comment]
Hi @brenc Have pushed the new version of the client. let me know if this fixing your issue!
