### ISSUE TITLE
CDN-hosted version of the mistralai JS SDK?

### ISSUE THREAD

**Issue by maudnals** [mistralai/client-js#45]
Hi folks!
For quick frontend-only experimentation purposes, it would be handy to be able to write code like this:
```html
<script type="importmap">
  {
    "imports": {
      "@mistralai/mistralai": "https://{$CDN_HOSTED_LIB_URL}"
    }
  }
</script>
<script type="module">
  import MistralClient from '@mistralai/mistralai';
  const client = new MistralClient($API_KEY);
  // const chatResponseGen = await client.chat({ ... etc
</script>
```
It would require a CDN-hosted version of @mistralai/mistralai.
Is it an option for you to support something like this?

Note: No server / node component here, so the API key lives in the frontend. Arguably OK for quick local experimentation purposes.

**Comment by Achintharya** [comment]
you can use skypackcdn to import from, that's what I used on my website. It was working perfectly fine until today. The zod version is not updated so it isnt working currently

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
