### ISSUE TITLE
Continous retry on hitting rate limit

### ISSUE THREAD

**Issue by ptrrrr** [mistralai/client-js#46]
The rate limit response code is 429 and is one of the retry code in

const RETRY_STATUS_CODES = [429, 500, 502, 503, 504];

So this is continous retry cycle 

        } else if (RETRY_STATUS_CODES.includes(response.status)) {
          console.debug(
            `Retrying request on response status: ${response.status}`,
            `Response: ${await response.text()}`,
            `Attempt: ${attempts + 1}`,
          );
          // eslint-disable-next-line max-len
          await new Promise((resolve) =>
            setTimeout(resolve, Math.pow(2, (attempts + 1)) * 500),
          );
          
        I had like 50 requests in a few seconds.  The more requests I make, the more the rate limit is triggered.  
        
        So either we should change the response code for rate liits or ideally do a sliding window retry with extended delays.

**Comment by OlegIvaniv** [comment]
We're also running into this. On the website, you say the request limit is 5 per second, and the input limit is 2mil per minute. So if there are 20 requests, it should take ~ 4 seconds. Instead, it takes 150 seconds to complete all the retries.  It almost seems like the retry requests are counting toward the rate limit

**Comment by sneko** [comment]
Since the team is not responding, I advise you to use something like `patch-package` (https://github.com/ds300/patch-package) to patch the package when installed (in your case, it would remove the 429 from the array). It saves time for sure 👍

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
