### ISSUE TITLE
Add support for aborting (preferably via AbortSignal)

### ISSUE THREAD

**Issue by sublimator** [mistralai/client-js#5]

**Comment by wordware-ai** [comment]
Available here: https://www.npmjs.com/package/mistral-edge
Just pass an abort signal into the config parameter

e.g.
```typescript
const abortController = new AbortController();
const tokenStream = streamMistralChat(
    [{ role: "user", content: "Write a haiku about cheese" }],
    {
      model: "mistral-medium",
      temperature: 0.7,
    },
    {
      signal: abortController.signal
    }
);

// Do what you like with the stream and abort it if needed
```

**Comment by sneko** [comment]
In addition to using explicitly the `signal` property, it would be great if the library was really dealing with the `timeout` property. Currently it has no impact and it defaults to 5 minutes of timeout...

I had to patch with `patch-package` to work around thanks to a signal:
```ts
    const url = `${this.endpoint}/${path}`;
    const options = {
      method: method,
      ...
      timeout: this.timeout * 1000, // Not working whereas it's written by their core team
      signal: AbortSignal.timeout(this.timeout * 1000), // This should do the trick
    };
```

@Bam4d it would be great if this repo could have more love from the core team. (cf. https://github.com/mistralai/client-js/graphs/contributors)
