### ISSUE TITLE
Client does not return a response

### ISSUE THREAD

**Issue by chanmathew** [mistralai/client-js#50]
Hi there,

Running the latest version of the SDK 0.1.3, but when I try to init and call the client, it does not return anything.

Here is my code:
```ts
const mistral = new MistralClient(env.PUBLIC_MISTRAL_API_KEY)
const response = await mistral.chatStream({
	model: 'mistral-large-latest',
	messages: [{ role: 'system', content: 'Say hello world.' }],
	temperature: 0
})

// response is an empty object {}
```

**Comment by ytimocin** [comment]
I can give this one a try.

**Comment by ptesny** [comment]
chatStream is a [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)

**Comment by sublimator** [comment]
This is not necessary. You are supposed to use as so:
https://github.com/mistralai/client-js/blob/649923634ff7302f2e7c58c505cbe5cb3a431c68/examples/chat_with_streaming.js#L1-L18

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
