### ISSUE TITLE
Refactor arrow function class methods for better inheritance support

### ISSUE THREAD

**Issue by JUNIORCO** [mistralai/client-js#58]
In `MistralClient`, you're using arrow functions for defining class methods. This limits the ability to easily override these methods in subclasses, for example if I want to have a class like:

```typescript
import MistralClient from "@mistralai/mistralai";

class ExtendedMistral extends MistralClient {
  constructor(apiKey: string, endpoint: string) {
    super(apiKey, endpoint);
  }

  override async chat(options: ChatOptions): Promise<ChatCompletionResponse> {
    // some extra logic here
    console.log("override");

    return await super.chat(options);
  }
}
```

Arrow functions in JavaScript bind `this` to the context of where they're defined, not where they're called. This means when you define class methods as arrow functions, they ignore the class hierarchy's `this` context, making it impossible to override these methods in subclasses.

If `chat` is an arrow function, it's tied to the original MistralClient instance's context. ExtendedMistral cannot override it because `super.chat(options)` tries to access a method on the MistralClient prototype, which doesn't exist.

Changing chat to a traditional method (`async chat(options) { ... }`) allows it to be part of the class's prototype, enabling `this` and `super` to correctly refer to ExtendedMistral when overridden.

So instead of doing this in MistralClient:

```typescript
chat = async function(options) {
  // Implementation
}
```

Do this:

```typescript
async chat(options) {
  // Implementation
}
```

I could take this on if needed.

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
