### ISSUE TITLE
getting err @mistralai/mistralai v 0.1.3 doesn't support require way of importing library. i want to know the version of library which support it.

### ISSUE THREAD

**Issue by Devmindtk** [mistralai/client-js#59]
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules\@mistralai\mistralai\src\client.js not supported. Instead change the require of client.js to a dynamic import() which is available in all CommonJS modules.

**Comment by nico-crest** [comment]
Reproductible error here. 
`const mistralai_1 = require("@mistralai/mistralai");
                    ^
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@mistralai/mistralai/src/client.js from dist/app.service.js not supported.
Instead change the require of client.js in cnc-scraping/dist/app.service.js to a dynamic import() which is available in all CommonJS modules.`
Should we roll back to prior version ?

**Comment by Devmindtk** [comment]
what do you mean by dynamic import?

**Comment by popmatik** [comment]
Also seeing this issue. Any resolution in the pipeline please?

**Comment by nbonamy** [comment]
Seeing the same in an Electron app using vite.

**Comment by zognotadog** [comment]
Also seeing this issue when importing in typescript:

```typescript
import  MistralClient from '@mistralai/mistralai';

const apiKey = process.env.MISTRAL_API_KEY;

const client = new MistralClient(apiKey);
```

**Comment by masad08** [comment]
same issue. any luck on why/fix?

**Comment by kndpt** [comment]
Same issue

**Comment by Bogatinovski** [comment]
We have identical error when trying to import in a typescript project. Any workaround?

**Comment by nbonamy** [comment]
> We have identical error when trying to import in a typescript project. Any workaround?

For now I just copied index.js in my project renamed it and imported it. Works for me.

**Comment by ptesny** [comment]
@Devmindtk , you can find in this blogpost [Mistral gagnant. Mistral AI and SAP Kyma serverless.](https://community.sap.com/t5/technology-blogs-by-sap/mistral-gagnant-mistral-ai-and-sap-kyma-serverless/ba-p/13676997)) a full working solution of combining mistralai into a CJS module.

PS. Full recipe: [mistral gagnant](https://gist.github.com/ptesny/cb7189bc0fec9fab8d71189952e5edd8#3-mistral-gagnant)

**Comment by ptesny** [comment]
> Reproductible error here. `const mistralai_1 = require("@mistralai/mistralai"); ^ Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@mistralai/mistralai/src/client.js from dist/app.service.js not supported. Instead change the require of client.js in cnc-scraping/dist/app.service.js to a dynamic import() which is available in all CommonJS modules.` Should we roll back to prior version ?

@nico-crest , 
to address the reported [error](https://gist.github.com/ptesny/cb7189bc0fec9fab8d71189952e5edd8#22-err_require_esm-error-when-trying-to-requiremistralaimistralai)

please refer to my previous [comment](https://github.com/mistralai/client-js/issues/59#issuecomment-2067951881)

**Comment by MaxDesplanches** [comment]
same issue here on 0.3

**Comment by Robouste** [comment]
> > We have identical error when trying to import in a typescript project. Any workaround?
> 
> For now I just copied index.js in my project renamed it and imported it. Works for me.

What index.js are you talking about? Can you provide more guidance?

**Comment by ptesny** [comment]
@Robouste 
I have already provide a [solution](https://gist.github.com/ptesny/cb7189bc0fec9fab8d71189952e5edd8#3-mistral-gagnant) in this [thread](https://github.com/mistralai/client-js/issues/59#issuecomment-2067951881)

**Comment by Robouste** [comment]
@ptesny  I know, I went through it but I don't see how to implement it with nestjs as I don't really understand it to be honest :)

In the end I went the old fashion way and call their API directly using axios

**Comment by nbonamy** [comment]
> > > We have identical error when trying to import in a typescript project. Any workaround?
> > 
> > 
> > For now I just copied index.js in my project renamed it and imported it. Works for me.
> 
> What index.js are you talking about? Can you provide more guidance?

`src/client.js`

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
