### ISSUE TITLE
mistralClient types dont contain `maxRetries` nor `timeout` 

### ISSUE THREAD

**Issue by saikatmitra91** [mistralai/client-js#62]
Is there a specific reason for not exposing `maxRetries` from MistralClient ? 

also I do see `timeout` parameter is passed to fetch options but dont think thats a valid parameter as per docs 
https://developer.mozilla.org/en-US/docs/Web/API/fetch. Might be moving to typescript can fix such issues. 

If these are just misses, happy to submit a PR to fix this issue.

**Comment by alexgirin** [comment]
@fuegoio Hello. Can you please provide some estimates when this will be released. Thanks.

**Comment by fuegoio** [comment]
> @fuegoio Hello. Can you please provide some estimates when this will be released. Thanks.

Hi! It has just been released in the 0.2.0.
