### ISSUE TITLE
`.files` is missing from types

### ISSUE THREAD

**Issue by arcticfly** [mistralai/client-js#82]
Hey Mistral team,

I'm excited to try out your fine-tuning API! Unfortunately it appears that the `.files` attribute (necessary for uploading a training file to the API before training) is missing from the TypeScript types. Some documentation is available on the npm [README](https://www.npmjs.com/package/@mistralai/mistralai), but it's currently up to the developer to guess what the types are and define them ourselves.

Could you please ship the updated types? Thank you!

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
