### ISSUE TITLE
Remove node-fetch as a dependency

### ISSUE THREAD

**Issue by jwerre** [mistralai/client-js#83]
I see that node-fetch is used to make request to the Mistral API. Since [node-fetch doesn't support CommonJs](https://www.npmjs.com/package/node-fetch) it would be pretty easy to remove it as a dependency. And, even better, you'd have zero dependencies. All you need to do is import the native `https` module and replace [`_request`](https://github.com/mistralai/client-js/blob/5efba3b91f7582b13022c7c556157e08e8650a6c/src/client.js#L110) with this:

```ts
import { request } from 'https';

async _request<T, U>(
	method: string,
	path: string,
	body?: U,
	retries: number = 0
): Promise<T> {
	const options = {
		method,
		port: 443,
		body: method !== 'get' && body ? JSON.stringify(body) : null,
		headers: {
			'User-Agent': `mistral/mistral-client`,
			Accept: 'application/json',
			'Content-Type': 'application/json',
			Authorization: `Bearer ${this.apiKey}`,
		},
	};
	const url = new URL(`${this.endpoint}/${path}`);

	return new Promise((resolve, reject) => {
		const req = request(url, options, (res) => {
			let data = '';

			res.on('data', (chunk) => {
				data += chunk;
			});

			res.on('end', () => {
				if (
					RETRY_STATUS_CODES.includes(res.statusCode ?? 500) &&
					retries < this.maxRetries
				) {
					console.debug(
						`Retry ${retries + 1}/${
							this.maxRetries
						} - Status Code: ${res.statusCode}`
					);
					setTimeout(() => {
						resolve(
							this._request<T, U>(
								method,
								path,
								body,
								retries + 1
							)
						);
					}, RETRY_DELAY_MS);
				} else {
					resolve(JSON.parse(data) as T);
				}
			});
		});

		req.on('error', (err) => {
			if (retries < this.maxRetries) {
				console.debug(
					`Retry ${retries + 1}/${this.maxRetries} - Error: ${
						err.message
					}`
				);
				setTimeout(() => {
					resolve(
						this._request<T, U>(method, path, body, retries + 1)
					);
				}, RETRY_DELAY_MS);
			} else {
				reject(new MistralAPIError(err.message));
			}
		});

		if (options.body) {
			req.write(options.body);
		}

		req.setTimeout(this.timeout, () => {
			req.destroy();
			if (retries < this.maxRetries) {
				console.log(
					`Retry ${retries + 1}/${this.maxRetries} - Timeout`
				);
				setTimeout(() => {
					resolve(
						this._request<T, U>(method, path, body, retries + 1)
					);
				}, RETRY_DELAY_MS);
			} else {
				reject(new MistralAPIError('Request timed out'));
			}
		});

		req.end();
	});
}
```

Happy to make a PR once #73 is merged

**Comment by alex-shortt** [comment]
Yeah had to make my own api wrapper, this was killing my builds. Was able to swap `node-fetch` with https://www.npmjs.com/package/node-fetch-commonjs

**Comment by jwerre** [comment]
> Yeah had to make my own api wrapper, this was killing my builds. Was able to swap `node-fetch` with https://www.npmjs.com/package/node-fetch-commonjs

You could try using [Fetch v2](https://www.npmjs.com/package/node-fetch#commonjs)

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
