### ISSUE TITLE
Having issues with overriding MistralCilent from @mistralai/mistralai methods using typescript

### ISSUE THREAD

**Issue by I560263** [mistralai/client-js#85]
I am currently facing this error 
Error [ERR_REQUIRE_ESM]: require() of ES Module to a dynamic import() which is available in all CommonJS modules when I try to import MistralClient from '@mistralai/mistralai';

**Comment by Muhammad-Owais-Warsi** [comment]
If you are using import(), you should check your package.json to see if it has "type": "module"

**Comment by ilies-t** [comment]
I have the same issue, due to our TypeScript environment, we cannot set `"type": "module"`.
Unfortunately, the only solution was to implement Mistral AI API calls using Axios

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
