### ISSUE TITLE
Logits analysis with Mistral models

### ISSUE THREAD

**Issue by lucas-vitrus** [mistralai/client-js#86]
Hi all, 

Is there a way with the Mistral API (js or py) to get output token information to plot something like this?

![image](https://github.com/mistralai/client-js/assets/133435610/6f3f7ca5-e464-40cc-b14f-6d3f62ea6349)
[Anthropic, Golden Gate blog post](https://www.anthropic.com/news/mapping-mind-language-model)

**Comment by fuegoio** [comment]
Hi, thanks for your feedback. It is possible to get this information from our API currently. This requires access to a deeper level in the model that is not exposed.
