### ISSUE TITLE
Zod version is not up-to-date

### ISSUE THREAD

**Issue by Achintharya** [mistralai/client-js#88]
I'm getting this error while using skypackcdn to use on my website, I think the zod version is not up-to-date i.e v3.23.8 which has a en.ts file instead of en.d.ts. I checked in the package.json and the zod version is 3.23.4 there

**

> build:zod@v3.23.8-07yem4v67JRURwIbJ6iX?from=@mistralai/mistralai:16  [Package Error] "zod@v3.23.8" could not be built. (Imported by "@mistralai/mistralai").
> [1/5] Verifying package is valid…
> [2/5] Installing dependencies from npm…
> [3/5] Building package using esinstall…
> Running esinstall...
> Cannot find module 'zod/locales/en.d.ts'

**

**Comment by GaspardBT** [comment]
Thanks for reporting this issue. We have **deprecated** this package in favor of [mistralai/client-ts](https://github.com/mistralai/client-ts), which is the new official Mistral client, **compatible** with both TypeScript and JavaScript.

You can find all installation information [here](https://github.com/mistralai/client-ts?tab=readme-ov-file#sdk-installation).

This change is effective starting with version 1.0.0 of the [npm package](https://www.npmjs.com/package/@mistralai/mistralai?activeTab=readme).

Let us know if your issue persists with the new package by opening an issue there.
