### ISSUE TITLE
No stopping conditions

### ISSUE THREAD

**Issue by nyacg** [mistralai/client-js#9]
It seems it is not possible to set stop sequences with the Mistral API. This is a very common pattern when running inference on LLMs to have some fine-grained control over the output - e.g. [OpenAI](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop).

This isn't just an issue with the JS client, it seems there aren't stop sequences in the [REST API](https://docs.mistral.ai/api/) either.

Is this feature coming soon? If not what's the reasoning behind that?

Thanks!

**Comment by Bam4d** [comment]
Currently we do not support stop tokens. 

Can you explain your use case more so we can understand what you are using the stop tokens for?

Thanks

**Comment by nyacg** [comment]
Sure, it's a very common pattern to use them to limit the output to be more constrained. 

e.g. Setting the stop token to be a full stop "." will end the generation after the first sentence 

It's extremely helpful when building agents because they tend to do things like hallucinate the results of an API call so you can set the stop token to 'Observation:' (in a ReAct agent) and this forces the LLM to stop generating at that point
